node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'latest') {
       sh 'npm install'
       sh 'npm test'
     }
   }

  stage('Build image') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */
         def app = docker.build("bisnaisu/docker-example:${commit_id}", '.')
  }
   stage('docker build/push') {
     docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
      //  def app = docker.build("bisnaisu/docker-example:${commit_id}", '.').push()
      app.push("latest")
     }
   }
}
